# Come nginx gestisce connessioni a basso livello
events {
    worker_connections 1024; # per ogni worker process massimo 1024 connessioni simultanee
}

http {
    # non usare: unico entry point da subject: 443
    # Server virtuale - redirect da HTTP a HTTPS
    # server {
    #     listen 80;
    #     server_name plichota.42.fr;
    #     return 301 https://$host$request_uri;
    # }

    # Server HTTPS principale
    server {
        listen 443 ssl;
        server_name plichota.42.fr;

        ssl_certificate     /etc/nginx/ssl/cert.pem;
        ssl_certificate_key /etc/nginx/ssl/key.pem;
        ssl_protocols       TLSv1.2 TLSv1.3;

        root /var/www/html;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
            fastcgi_pass wordpress:9000;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}